import type { ChecklistCategory } from "./types";

export interface ChecklistPreset {
  key: string;
  name: string;
  category: ChecklistCategory;
  description: string;
  items: string[];
}

export const CHECKLIST_PRESETS: ChecklistPreset[] = [
  {
    key: "pre_job",
    name: "Pre-Job — Mobile Setup",
    category: "pre_job",
    description:
      "Run before leaving home. Mobile detailing has zero tolerance for forgotten gear — there's no going back to the shop.",
    items: [
      "Confirm appointment time + customer phone number",
      "Confirm address — open in Maps, check parking/driveway access",
      "Confirm water access on site (hose bib, spigot location)",
      "Confirm power access on site, or load generator + extension cord",
      "Check weather — reschedule if rain expected during job",
      "Charge polisher, vacuum, wet/dry vac, work light",
      "Fill water tank (if using self-contained setup)",
      "Refill chemical bottles: APC, wheel cleaner, glass cleaner, dressing, sealant/wax",
      "Pack foam cannon + hose + pressure washer",
      "Pack microfiber towels sorted by task: paint / glass / interior / wheels / dressing",
      "Pack pads, brushes, detail brushes, applicators",
      "Pack trash bags, paper towels, gloves",
      "Confirm gas in vehicle, payment app ready",
      "Take before photos when you arrive — walk the whole car",
    ],
  },
  {
    key: "exterior",
    name: "Exterior Detail",
    category: "exterior",
    description:
      "Top-down, contamination-first. The order keeps you from re-contaminating clean panels and avoids water spots.",
    items: [
      "Walk-around with customer — note scratches, chips, oxidation",
      "Before photos: full car + any problem areas",
      "Set up water source / pressure washer",
      "Pre-rinse entire vehicle top to bottom (cool the paint)",
      "Wheels & tires: wheel cleaner spray + soft wheel brush + lug nut brush",
      "Wheel wells: APC spray + fender brush",
      "Rinse wheels + arches thoroughly",
      "Foam cannon pre-soak — top to bottom, let dwell 3–5 min",
      "Two-bucket contact wash: grit guard in both, mitt top to bottom",
      "Rinse top to bottom (no air-dry — causes water spots)",
      "Bug + tar remover on front bumper, lower rocker panels, mirrors",
      "Clay bar on paint if contaminated (lubricate, light pressure)",
      "Dry with plush drying towel + leaf blower for door jambs and mirrors",
      "Wipe door jambs, trunk lip, hood lip",
      "Apply spray sealant or paint wax in cross-hatch pattern, buff off",
      "Tire shine: apply, let flash 2 min, wipe excess",
      "Exterior glass: ammonia-free cleaner, two-towel wipe method",
      "Chrome + trim dressing if applicable",
      "Final walk-around in sunlight — check for missed spots, streaks",
      "After photos: full car + previously noted problem areas",
    ],
  },
  {
    key: "interior",
    name: "Interior Detail",
    category: "interior",
    description:
      "Top-down, dry before wet, glass last. Vacuuming after wiping surfaces means debris falls twice — do hard surfaces first.",
    items: [
      "Remove all trash, loose items, floor mats",
      "Compressed air blow-out: vents, seat tracks, center console seams, cup holders",
      "Vacuum headliner (if dusty), pillars, sun visors",
      "Vacuum seats thoroughly — between cushions, along seams",
      "Vacuum carpet, floor mats separately with stiff brush",
      "Vacuum trunk + under mats",
      "APC + microfiber on dashboard, top to bottom",
      "APC on door panels, armrests, door pockets",
      "Center console + cup holders deep clean (brush + APC)",
      "Detail brush: vents, buttons, gauge cluster, stitching, badging",
      "Steering wheel: leather cleaner or APC depending on material",
      "Spot-treat any fabric stains (enzyme cleaner, blot + extract)",
      "Leather seats: leather cleaner + conditioner if applicable",
      "Plastic trim: 303 Aerospace or UV protectant dressing",
      "Door sills + jambs wiped",
      "Interior glass: ammonia-free, two-towel method (inside of windshield especially)",
      "Replace mats, return personal items",
      "Light odor neutralizer if needed (not air freshener over a problem)",
      "Final smell check — no chemical smell should linger",
    ],
  },
  {
    key: "full_detail",
    name: "Full Detail — Best-Path Order",
    category: "full_detail",
    description:
      "Exterior while interior dries, interior last so no footprint contamination. Longest detail type — before photos are critical.",
    items: [
      "Walk-around with customer — set expectations on stains, chips, scratches",
      "Before photos: all panels, interior, any damage",
      "Trash-out interior, remove mats",
      "Set up water + power",
      "Pre-rinse exterior",
      "Wheels, arches, foam, contact wash",
      "Rinse + dry exterior",
      "Clay bar if needed",
      "Spray sealant / wax + tire shine + exterior glass",
      "Move to interior — blow-out vents + cracks",
      "Vacuum seats, carpet, mats, trunk",
      "APC pass: dash, doors, console, trim",
      "Detail brush vents + buttons",
      "Spot-treat any stains",
      "Leather conditioner if applicable",
      "Plastic dressing on all trim",
      "Door sills + jambs",
      "Interior glass",
      "Final exterior check — re-wipe anything that re-spotted",
      "After photos: full exterior + interior key areas",
      "Walk-around with customer for approval",
    ],
  },
  {
    key: "interior_restoration",
    name: "Interior Restoration — Deep Reset",
    category: "interior_restoration",
    description:
      "For heavily soiled interiors. Document everything before touching — photos protect you and set customer expectations.",
    items: [
      "Walk-around with customer — confirm scope and pricing",
      "Before photos: every stain, damaged panel, odor source",
      "Remove all trash + belongings (bag and label if not trash)",
      "Remove floor mats, pull seats if safe + needed for carpet access",
      "Compressed air blow-out: vents, seat tracks, all crevices",
      "Pet hair removal: rubber brush + high-suction vacuum",
      "Initial vacuum pass — get everything loose",
      "Pre-treat heavy stains with enzyme or upholstery cleaner, dwell 5 min",
      "Hot-water extraction on seats + carpet (multiple passes on worst areas)",
      "Re-treat and re-extract any remaining stains",
      "Headliner spot-clean only — never saturate",
      "Crevice deep-clean: console seams, seat tracks, behind pedals",
      "Hard-surface APC (more aggressive than standard detail)",
      "Leather deep-clean + condition if applicable",
      "Odor treatment: enzyme spray + let dry, ozone if agreed with customer",
      "Allow drying time — windows cracked, fans running",
      "Final plastic dressing on all trim",
      "Interior glass",
      "Reinstall seats + mats",
      "After photos showing the improvement",
      "Walk-around with customer — let them inspect",
    ],
  },
  {
    key: "paint_correction",
    name: "Paint Correction — Single Stage",
    category: "exterior",
    description:
      "One compounding pass to remove light swirls and oxidation. Decontaminate fully before touching a pad to paint.",
    items: [
      "Before photos in direct sunlight + cross-light to show swirls/scratches",
      "Full exterior wash: foam + contact wash + rinse + dry",
      "Iron decontamination spray — full panel, let bleed, rinse",
      "Clay bar entire vehicle (lubricate well, light pressure)",
      "Rinse + dry again — paint must be bone dry before polishing",
      "Panel wipe with IPA or panel prep spray (removes any residue)",
      "Tape off trim, plastic, rubber edges",
      "Set up polisher: DA or rotary, compound pad",
      "Work panel by panel — spread compound, work on speed 4–5",
      "Wipe off compound residue with clean microfiber after each panel",
      "Inspect each panel with work light in cross-light before moving on",
      "Switch to finishing polish + finishing pad for any haze",
      "Final panel wipe with IPA to check true correction result",
      "Apply paint sealant or carnauba wax for protection",
      "Exterior glass, trim dressing, tire shine",
      "After photos in same lighting as before — show the difference",
      "Walk-around with customer in sunlight",
    ],
  },
  {
    key: "ceramic_prep",
    name: "Ceramic Coating Prep",
    category: "exterior",
    description:
      "Coating is only as good as the prep. Every step here matters — coating locks in whatever is on the paint.",
    items: [
      "Full paint correction pass completed first (see Paint Correction checklist)",
      "Foam + contact wash with coating-safe shampoo (no wax)",
      "Iron decontamination spray + rinse",
      "Clay bar + rinse + dry",
      "Panel wipe with IPA 50/50 — every single panel including door jambs",
      "Check each panel with work light — no oil, no water, no residue",
      "Tape off rubber trim, plastic, badges, glass edges",
      "Work in shade or controlled environment — no direct sun, no wind",
      "Apply coating panel by panel with suede applicator block",
      "Flash time per product instructions (typically 1–3 min) before leveling",
      "Level with clean low-lint microfiber, light pressure",
      "Inspect with work light — no streaks, no high spots",
      "Let cure per product spec before any water contact",
      "Apply second coat on horizontal panels (hood, roof, trunk) after first cures",
      "Document cure time + warranty info for customer",
      "After photos + share coating care instructions with customer",
    ],
  },
  {
    key: "engine_bay",
    name: "Engine Bay Detail",
    category: "exterior",
    description:
      "Degrease then rinse — cold engine, plastic covers on electrics. Never pressure-wash directly on sensors or fuse boxes.",
    items: [
      "Engine must be cold (not driven recently)",
      "Cover alternator, fuse box, air intake, exposed electrical connectors",
      "Pre-rinse engine bay with low-pressure water — light mist only",
      "Apply degreaser (APC or engine degreaser) to greasy areas, dwell 3–5 min",
      "Brush: engine block, valve cover, hoses, brackets (stiff detailing brush)",
      "Detail brush around sensors, wiring harnesses, tight spots",
      "Low-pressure rinse — avoid direct spray on covered electrical areas",
      "Dry with compressed air + microfiber",
      "Remove plastic covers",
      "Dress plastic covers, hoses, rubber components with dressing",
      "Wipe engine block if accessible",
      "Check for any leaks or damage while cleaning — note for customer",
      "Final photos of finished engine bay",
    ],
  },
  {
    key: "post_job",
    name: "Post-Job — Wrap & Follow-Up",
    category: "post_job",
    description:
      "Two minutes of admin here turns a one-time job into repeat business. Don't skip the review request.",
    items: [
      "Walk-around with customer — get verbal approval",
      "After photos in good light (multiple angles, interior + exterior)",
      "Collect payment — log amount in app",
      "Send Google review link (use saved template)",
      "Mention monthly maintenance plan if they're not already on one",
      "Set follow-up reminder 4–6 weeks out in app",
      "Mark appointment complete in app",
      "Pack all gear — count microfibers, no chemicals left on-site",
      "Rinse foam cannon, wipe down polisher pads before loading",
      "Log any product used heavily so you can restock",
    ],
  },
  {
    key: "equipment_weekly",
    name: "Equipment — Weekly Maintenance",
    category: "equipment",
    description:
      "End-of-week reset. A 20-minute routine prevents a Saturday morning failure on the customer's driveway.",
    items: [
      "Empty + rinse extractor tank",
      "Flush extractor lines with clean water, run until clear",
      "Empty vacuum — tap out or replace filter",
      "Check vacuum hoses + attachments for cracks",
      "Drain pressure washer or run 30s to prevent freezing (winter)",
      "Wipe pressure washer pump + check oil level",
      "Check foam cannon nozzle — unclog if needed",
      "Wash dirty microfibers: separate loads by soil level, no fabric softener",
      "Hang microfibers to air-dry (never dry dirty ones)",
      "Restock chemical bottles for next week",
      "Replace worn pads, brushes, or applicators",
      "Check generator oil + fuel if used",
      "Confirm water tank is filled if needed for next job",
      "Check tire pressure on work vehicle",
    ],
  },
];

export function findPreset(key: string): ChecklistPreset | undefined {
  return CHECKLIST_PRESETS.find((p) => p.key === key);
}
